### ISSUE TITLE
Programming with instance of

### ISSUE THREAD

**Issue by mmueller301** [FraunhoferCESE/madcap#122]
```
CellLocationProbe createCellLocationProbe(CellLocation location){
        if (location instanceof GsmCellLocation) {
            GsmCellLocation gcLoc = (GsmCellLocation) location;
            CellLocationProbe cellLocationProbe = new CellLocationProbe();
            cellLocationProbe.setDate(System.currentTimeMillis());
            cellLocationProbe.setCellType("GSM");
            cellLocationProbe.setAreaCode(gcLoc.getLac()+" ");
            return cellLocationProbe;
        } else if (location instanceof CdmaCellLocation) {
            CdmaCellLocation ccLoc = (CdmaCellLocation) location;
            CellLocationProbe cellLocationProbe = new CellLocationProbe();
            cellLocationProbe.setDate(System.currentTimeMillis());
            cellLocationProbe.setCellType("CDMA");
            cellLocationProbe.setAreaCode(ccLoc.getBaseStationId()+" ");
            cellLocationProbe.setLat((double) ccLoc.getBaseStationLongitude());
            cellLocationProbe.setLat((double) ccLoc.getBaseStationLatitude());
            return cellLocationProbe;
        } else {
            Log.i(TAG, "onCellLocationChanged: " + location.toString());
            CellLocationProbe cellLocationProbe = new CellLocationProbe();
            cellLocationProbe.setDate(System.currentTimeMillis());
            cellLocationProbe.setCellType("UNKNOWN");
            return cellLocationProbe;
        }
 }
```

(GsmCellLocation and CdmaCellLocation inherit from CellLocation)
Android Studio inspection does not like that style. I can imagine to decompose it into 3 methods with the 3 types of arguments (GsmCellLocation, CdmaCellLocation and CellLocation) but is that right? Does java automatically map the type to the 'most specific' type while evaluating which of the overloaded methods to take? Don't know how to google that.

**Comment by llayman** [comment]
Hi Marcel,

No, Java will not automatically determine the subtype of CellLocation and call the appropriate method.

Android Studio is mad at `instanceof` because use of `instanceof` is often a symptom of poor design. As you imply, the "correct" Java implementation would be to have a separate method for each subtype because how you process the object depends on the subtype. 

You can see in the documentation for https://developer.android.com/reference/android/telephony/TelephonyManager.html#getCellLocation() that they plan to deprecate this method. No doubt this is why Android has not improved the design. They recommend using https://developer.android.com/reference/android/telephony/TelephonyManager.html#getAllCellInfo(), which probably contains everything you need. However, that documentation says "This method is preferred over using getCellLocation(). However, for older devices, getAllCellInfo() may return null. In these cases, you should call getCellLocation() instead." 

So, at least on older devices, I do not think there is a way around using `instanceof`. It's not a big deal in this case, so I think you can add a suppression for this warning. However, we should prefer Android's recommended way of doing things, which would be to use `getAllCellInfo`.
