### ISSUE TITLE
System Listener

### ISSUE THREAD

**Issue by mmueller301** [FraunhoferCESE/madcap#126]
The system listener will be listening to interesting system events and refactor parts from the old StateProbe. Many different probes will be implemented and saved to the data base.

- [x] Dreaming Probe

- [x] Screen Probe

- [x] AirplaneMode Probe

**Comment by mmueller301** [comment]
@llayman what else should we capture here? Information for the system itself like device name, API version, something else?

**Comment by llayman** [comment]
@mmueller301 I would like to capture:

- Device make (e.g., Samsung)
- Device model (e.g., Galaxy S4)
- Android OS version or API level
- MADCAP version

This information does not necessarily need to be in this Probe since I do not think this information can change while change while Data Collection is on. Seems like this should be helpful: https://developer.android.com/reference/android/os/Build.html

**Comment by mmueller301** [comment]
I would be a new Probe anyway @llayman. Just a GeneralSystemProbe which I think just need to be captured whenever the DataCollectionService is on.

**Comment by mmueller301** [comment]
@llayman do we still want to capture: 

- `ACTION_BOOT_COMPLETED` (at the place where it was before it makes no sense anymore)

- `ACTION_HEADSET_PLUG` (maybe better in an AudioProbe?)

- `ACTION_SHUTDOWN`

- `ACTION_USER_PRESENT` - Sent when the user is present after device wakes up (e.g when the keyguard is gone).

**Comment by llayman** [comment]
@mmueller301 We definitely want the last 3. I think the first one is what triggers the OnBootCompleted listener. While we do not need to capture the `ACTION_BOOT_COMPLETED` intent specifically, it would be nice to know, in some way, that Data Collection started because BOOT COMPLETED vs. the user turned Data Collection On manually vs. the user Started the App. Does that make sense?

**Comment by mmueller301** [comment]
@llayman yes, I will think about how to pack those things into new probes. I would like to move the headset intent into any kind of headphone probe and not in the system listener. The boot and shutdown should go into a certain systemUptimeProbe and the user presence should be it's own probe I think.
