### ISSUE TITLE
Screen brightness probe? 

### ISSUE THREAD

**Issue by llayman** [FraunhoferCESE/madcap#89]

**Comment by mmueller301** [comment]
Screen Probe will have only screen mode (ON or OFF). We can just read the user's preference on the screen brightness but not what actual brightness it has. The intent therefore is only sent internally. Also related to #125

**Comment by llayman** [comment]
@mmueller301 Is the Screen Probe ON or OFF what is reported by Android, or does Android report the SCREEN LOCKED?

**Comment by mmueller301** [comment]
The intents we capture is ACTION_SCREEN_OFF and ACTION_SCREEN_ON. Both get also fired when you lock/unlock the screen. Is this what you meant @llayman ?

**Comment by llayman** [comment]
@mmueller301 Is there a way to distinguish when the Screen turns ON/OFF due to user activity, such as pressing the power button?

**Comment by mmueller301** [comment]
Partially. We can determine if the screen turned off due to user inactivity when there was before a dreaming probe with ON. Anyhow it looks like there is no power button pressed intent. All solutions I saw so far are invoking the screen on and off everytime to determine if the button might have been pressed.  We can make a custom key pressed listener, but I would not recommend to do this unless it is really really important, because this listener has to listen ACTIVELY to the button which will be energy consuming. There might be another solution which I havn't found yet. What do you think @llayman

**Comment by llayman** [comment]
It would be nice to capture when the Power Button is pressed, but I don't want to eat battery to do it. The Screen On/Off is fine for now.
